language: python
python:
  - "3.4"
install:
  - python setup.py install
script: nosetests-3.4
env:
  - RUNENV=travis MAL_USERNAME=py3mal MAL_PASSWORD=nepszerujelszo TESTS_SQUID_ADDRESS=celestia.pushrbx.net:3128